services:
  dtf_devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: d-trees-and-forests
    user: dev
    volumes:
      - ..:/app
      - home:/home/dev
    ports:
      - "3000:3000"
    working_dir: /app
    stdin_open: true
    tty: true

volumes:
  home:
