services:
  dtf_devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    platform: linux/amd64
    container_name: d-trees-and-forests
    user: dev
    volumes:
      - ..:/app
      - home:/home/dev
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
      - 3003:3003
      - 3004:3004
      - 3005:3005
    working_dir: /app
    stdin_open: true
    tty: true

volumes:
  home:
